agent:
  script_url: https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh

providers:
  linode:
    image: linode/ubuntu20.04
    key: <LINODE_API_KEY>
    type_slug: g6-dedicated-2
