agent:
  script_url: https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh

openvpn:
  path:
    darwin: openvpn
    linux: openvpn
    windows: C:\Program` Files\OpenVPN\bin\openvpn.exe

providers:
  linode:
    image: linode/ubuntu20.04
    key: <LINODE_API_KEY>
    type_slug: g6-dedicated-2
