@startuml

hide footbox

actor       You         as u
participant autovpn.exe as a
participant Linode      as l

u -> a: Start ("autovpn linode eu-central")
activate a
a -> l: Creates VPN
activate l
l --> a: VPN created
a -> l: Connects to VPN\nwith OpenVPN
... A secure* browsing session later ...
u -> a: Quit ("CTRL+C")
a -> l: Destroy VPN
l --> a: VPN destroyed
destroy l
a --> u: Done!
deactivate a

@enduml
