name: Release binaries

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-alpha.*"
      - "*.*.*-beta.*"
      - "*.*.*-rc.*"

env:
  GO_VERSION: ^1.20.4

jobs:
  build:
    name: Build
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [386, amd64, arm, arm64]
        exclude:
          - goos: darwin
            goarch: 386
          - goos: darwin
            goarch: arm
          - goos: windows
            goarch: arm

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-X 'main.version=${{ github.ref_name }}'"

      - name: Create tarball
        if: ${{ matrix.goos != 'windows' }}
        run: |
          sha256sum autovpn README.md LICENSE default.config.yml docs/connect_seq_simplified.png > sha256sums.txt
          tar -czvf autovpn_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz autovpn README.md LICENSE default.config.yml sha256sums.txt docs/connect_seq_simplified.png

      - name: Create zipfile
        if: ${{ matrix.goos == 'windows' }}
        run: |
          sha256sum autovpn.exe README.md LICENSE default.config.yml docs/connect_seq_simplified.png > sha256sums.txt
          zip autovpn_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip autovpn.exe README.md LICENSE default.config.yml sha256sums.txt docs/connect_seq_simplified.png

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            *.tar.gz
            *.zip

  release:
    name: Release
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true
          files: |
            artifact/*.tar.gz
            artifact/*.zip
